language: python
cache: pip
sudo: required
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - pipenv run pytest --cov=arxiv --cov-report=term-missing arxiv
after_success:
  - coveralls
  - "./tests/lint.sh arxiv"
  - "./tests/style.sh arxiv"
  - "./tests/type-check.sh arxiv"
